/* THIS FILE IS GENERATED.  Original: nds32.xml */

#include "defs.h"
#include "osabi.h"
#include "target-descriptions.h"

struct target_desc *tdesc_nds32;
static void
initialize_tdesc_nds32 (void)
{
  struct target_desc *result = allocate_target_description ();
  struct tdesc_feature *feature;
  struct tdesc_type *field_type, *type;

  set_tdesc_architecture (result, bfd_scan_arch ("n1h"));

  feature = tdesc_create_feature (result, "org.gnu.gdb.nds32.core");
  tdesc_create_reg (feature, "r0", 0, 1, NULL, 32, "int");
  tdesc_create_reg (feature, "r1", 1, 1, NULL, 32, "int");
  tdesc_create_reg (feature, "r2", 2, 1, NULL, 32, "int");
  tdesc_create_reg (feature, "r3", 3, 1, NULL, 32, "int");
  tdesc_create_reg (feature, "r4", 4, 1, NULL, 32, "int");
  tdesc_create_reg (feature, "r5", 5, 1, NULL, 32, "int");
  tdesc_create_reg (feature, "r6", 6, 1, NULL, 32, "int");
  tdesc_create_reg (feature, "r7", 7, 1, NULL, 32, "int");
  tdesc_create_reg (feature, "r8", 8, 1, NULL, 32, "int");
  tdesc_create_reg (feature, "r9", 9, 1, NULL, 32, "int");
  tdesc_create_reg (feature, "r10", 10, 1, NULL, 32, "int");
  tdesc_create_reg (feature, "r11", 11, 1, NULL, 32, "int");
  tdesc_create_reg (feature, "r12", 12, 1, NULL, 32, "int");
  tdesc_create_reg (feature, "r13", 13, 1, NULL, 32, "int");
  tdesc_create_reg (feature, "r14", 14, 1, NULL, 32, "int");
  tdesc_create_reg (feature, "r15", 15, 1, NULL, 32, "int");
  tdesc_create_reg (feature, "r16", 16, 1, NULL, 32, "int");
  tdesc_create_reg (feature, "r17", 17, 1, NULL, 32, "int");
  tdesc_create_reg (feature, "r18", 18, 1, NULL, 32, "int");
  tdesc_create_reg (feature, "r19", 19, 1, NULL, 32, "int");
  tdesc_create_reg (feature, "r20", 20, 1, NULL, 32, "int");
  tdesc_create_reg (feature, "r21", 21, 1, NULL, 32, "int");
  tdesc_create_reg (feature, "r22", 22, 1, NULL, 32, "int");
  tdesc_create_reg (feature, "r23", 23, 1, NULL, 32, "int");
  tdesc_create_reg (feature, "r24", 24, 1, NULL, 32, "int");
  tdesc_create_reg (feature, "r25", 25, 1, NULL, 32, "int");
  tdesc_create_reg (feature, "r26", 26, 1, NULL, 32, "int");
  tdesc_create_reg (feature, "r27", 27, 1, NULL, 32, "int");
  tdesc_create_reg (feature, "fp", 28, 1, NULL, 32, "data_ptr");
  tdesc_create_reg (feature, "gp", 29, 1, NULL, 32, "data_ptr");
  tdesc_create_reg (feature, "lp", 30, 1, NULL, 32, "code_ptr");
  tdesc_create_reg (feature, "sp", 31, 1, NULL, 32, "data_ptr");
  tdesc_create_reg (feature, "pc", 32, 1, NULL, 32, "code_ptr");
  tdesc_create_reg (feature, "d0lo", 33, 1, NULL, 32, "int");
  tdesc_create_reg (feature, "d0hi", 34, 1, NULL, 32, "int");
  tdesc_create_reg (feature, "d1lo", 35, 1, NULL, 32, "int");
  tdesc_create_reg (feature, "d1hi", 36, 1, NULL, 32, "int");
  tdesc_create_reg (feature, "ifc_lp", 175, 1, NULL, 32, "code_ptr");

  feature = tdesc_create_feature (result, "org.gnu.gdb.nds32.user");
  tdesc_create_reg (feature, "itb", 184, 1, NULL, 32, "data_ptr");

  feature = tdesc_create_feature (result, "org.gnu.gdb.nds32.system");
  tdesc_create_reg (feature, "cr0", 37, 1, "cr", 32, "data_ptr");
  tdesc_create_reg (feature, "cr1", 38, 1, "cr", 32, "data_ptr");
  tdesc_create_reg (feature, "cr2", 39, 1, "cr", 32, "data_ptr");
  tdesc_create_reg (feature, "cr3", 40, 1, "cr", 32, "data_ptr");
  tdesc_create_reg (feature, "cr4", 41, 1, "cr", 32, "data_ptr");
  tdesc_create_reg (feature, "cr5", 42, 1, "cr", 32, "data_ptr");
  tdesc_create_reg (feature, "cr6", 43, 1, "cr", 32, "data_ptr");
  tdesc_create_reg (feature, "ir0", 44, 1, "ir", 32, "data_ptr");
  tdesc_create_reg (feature, "ir1", 45, 1, "ir", 32, "data_ptr");
  tdesc_create_reg (feature, "ir2", 46, 1, "ir", 32, "data_ptr");
  tdesc_create_reg (feature, "ir3", 47, 1, "ir", 32, "data_ptr");
  tdesc_create_reg (feature, "ir4", 48, 1, "ir", 32, "data_ptr");
  tdesc_create_reg (feature, "ir5", 49, 1, "ir", 32, "data_ptr");
  tdesc_create_reg (feature, "ir6", 50, 1, "ir", 32, "data_ptr");
  tdesc_create_reg (feature, "ir7", 51, 1, "ir", 32, "data_ptr");
  tdesc_create_reg (feature, "ir8", 52, 1, "ir", 32, "data_ptr");
  tdesc_create_reg (feature, "ir9", 53, 1, "ir", 32, "data_ptr");
  tdesc_create_reg (feature, "ir10", 54, 1, "ir", 32, "data_ptr");
  tdesc_create_reg (feature, "ir11", 55, 1, "ir", 32, "data_ptr");
  tdesc_create_reg (feature, "ir12", 56, 1, "ir", 32, "data_ptr");
  tdesc_create_reg (feature, "ir13", 57, 1, "ir", 32, "data_ptr");
  tdesc_create_reg (feature, "ir14", 58, 1, "ir", 32, "data_ptr");
  tdesc_create_reg (feature, "ir15", 59, 1, "ir", 32, "data_ptr");
  tdesc_create_reg (feature, "ir16", 170, 1, "ir", 32, "data_ptr");
  tdesc_create_reg (feature, "ir17", 171, 1, "ir", 32, "data_ptr");
  tdesc_create_reg (feature, "ir18", 173, 1, "ir", 32, "data_ptr");
  tdesc_create_reg (feature, "ir19", 174, 1, "ir", 32, "data_ptr");
  tdesc_create_reg (feature, "ir20", 176, 1, "ir", 32, "data_ptr");
  tdesc_create_reg (feature, "ir21", 177, 1, "ir", 32, "data_ptr");
  tdesc_create_reg (feature, "ir22", 178, 1, "ir", 32, "data_ptr");
  tdesc_create_reg (feature, "ir23", 179, 1, "ir", 32, "data_ptr");
  tdesc_create_reg (feature, "ir24", 180, 1, "ir", 32, "data_ptr");
  tdesc_create_reg (feature, "ir25", 181, 1, "ir", 32, "data_ptr");
  tdesc_create_reg (feature, "mr0", 60, 1, "mr", 32, "data_ptr");
  tdesc_create_reg (feature, "mr1", 61, 1, "mr", 32, "data_ptr");
  tdesc_create_reg (feature, "mr2", 62, 1, "mr", 32, "data_ptr");
  tdesc_create_reg (feature, "mr3", 63, 1, "mr", 32, "data_ptr");
  tdesc_create_reg (feature, "mr4", 64, 1, "mr", 32, "data_ptr");
  tdesc_create_reg (feature, "mr5", 65, 1, "mr", 32, "data_ptr");
  tdesc_create_reg (feature, "mr6", 66, 1, "mr", 32, "data_ptr");
  tdesc_create_reg (feature, "mr7", 67, 1, "mr", 32, "data_ptr");
  tdesc_create_reg (feature, "mr8", 68, 1, "mr", 32, "data_ptr");
  tdesc_create_reg (feature, "mr9", 69, 1, "mr", 32, "data_ptr");
  tdesc_create_reg (feature, "mr10", 70, 1, "mr", 32, "data_ptr");
  tdesc_create_reg (feature, "mr11", 182, 1, "mr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr0", 71, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr1", 72, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr2", 73, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr3", 74, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr4", 75, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr5", 76, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr6", 77, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr7", 78, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr8", 79, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr9", 80, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr10", 81, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr11", 82, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr12", 83, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr13", 84, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr14", 85, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr15", 86, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr16", 87, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr17", 88, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr18", 89, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr19", 90, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr20", 91, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr21", 92, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr22", 93, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr23", 94, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr24", 95, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr25", 96, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr26", 97, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr27", 98, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr28", 99, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr29", 100, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr30", 101, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr31", 102, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr32", 103, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr33", 104, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr34", 105, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr35", 106, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr36", 107, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr37", 108, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr38", 109, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr39", 110, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr40", 111, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr41", 112, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr42", 113, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr43", 114, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr44", 115, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr45", 116, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr46", 117, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr47", 118, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "dr48", 172, 1, "dr", 32, "data_ptr");
  tdesc_create_reg (feature, "pfr0", 119, 1, "pfr", 32, "data_ptr");
  tdesc_create_reg (feature, "pfr1", 120, 1, "pfr", 32, "data_ptr");
  tdesc_create_reg (feature, "pfr2", 121, 1, "pfr", 32, "data_ptr");
  tdesc_create_reg (feature, "pfr3", 122, 1, "pfr", 32, "data_ptr");
  tdesc_create_reg (feature, "fucpr", 123, 1, "system", 32, "data_ptr");
  tdesc_create_reg (feature, "dmar0", 124, 1, "dmar", 32, "data_ptr");
  tdesc_create_reg (feature, "dmar1", 125, 1, "dmar", 32, "data_ptr");
  tdesc_create_reg (feature, "dmar2", 126, 1, "dmar", 32, "data_ptr");
  tdesc_create_reg (feature, "dmar3", 127, 1, "dmar", 32, "data_ptr");
  tdesc_create_reg (feature, "dmar4", 128, 1, "dmar", 32, "data_ptr");
  tdesc_create_reg (feature, "dmar5", 129, 1, "dmar", 32, "data_ptr");
  tdesc_create_reg (feature, "dmar6", 130, 1, "dmar", 32, "data_ptr");
  tdesc_create_reg (feature, "dmar7", 131, 1, "dmar", 32, "data_ptr");
  tdesc_create_reg (feature, "dmar8", 132, 1, "dmar", 32, "data_ptr");
  tdesc_create_reg (feature, "dmar9", 133, 1, "dmar", 32, "data_ptr");
  tdesc_create_reg (feature, "dmar10", 134, 1, "dmar", 32, "data_ptr");
  tdesc_create_reg (feature, "racr0", 135, 1, "racr", 32, "data_ptr");
  tdesc_create_reg (feature, "idr0", 136, 1, "idr", 32, "data_ptr");
  tdesc_create_reg (feature, "idr1", 137, 1, "idr", 32, "data_ptr");
  tdesc_create_reg (feature, "secur0", 183, 1, "secur", 32, "data_ptr");

  feature = tdesc_create_feature (result, "org.gnu.gdb.nds32.audio");
  tdesc_create_reg (feature, "D0L24", 138, 1, NULL, 32, "int");
  tdesc_create_reg (feature, "D1L24", 139, 1, "audio", 32, "int");
  tdesc_create_reg (feature, "I0", 140, 1, "audio", 32, "int");
  tdesc_create_reg (feature, "I1", 141, 1, "audio", 32, "int");
  tdesc_create_reg (feature, "I2", 142, 1, "audio", 32, "int");
  tdesc_create_reg (feature, "I3", 143, 1, "audio", 32, "int");
  tdesc_create_reg (feature, "I4", 144, 1, "audio", 32, "int");
  tdesc_create_reg (feature, "I5", 145, 1, "audio", 32, "int");
  tdesc_create_reg (feature, "I6", 146, 1, "audio", 32, "int");
  tdesc_create_reg (feature, "I7", 147, 1, "audio", 32, "int");
  tdesc_create_reg (feature, "M1", 148, 1, "audio", 32, "int");
  tdesc_create_reg (feature, "M2", 149, 1, "audio", 32, "int");
  tdesc_create_reg (feature, "M3", 150, 1, "audio", 32, "int");
  tdesc_create_reg (feature, "M5", 151, 1, "audio", 32, "int");
  tdesc_create_reg (feature, "M6", 152, 1, "audio", 32, "int");
  tdesc_create_reg (feature, "M7", 153, 1, "audio", 32, "int");
  tdesc_create_reg (feature, "MOD", 154, 1, "audio", 32, "int");
  tdesc_create_reg (feature, "LB", 155, 1, "audio", 32, "int");
  tdesc_create_reg (feature, "LE", 156, 1, "audio", 32, "int");
  tdesc_create_reg (feature, "LC", 157, 1, "audio", 32, "int");
  tdesc_create_reg (feature, "ADM_VBASE", 158, 1, "audio", 32, "int");
  tdesc_create_reg (feature, "SHFT_CTL0", 159, 1, "audio", 32, "int");
  tdesc_create_reg (feature, "SHFT_CTL1", 160, 1, "audio", 32, "int");
  tdesc_create_reg (feature, "CB_CTL", 161, 1, "audio", 32, "int");
  tdesc_create_reg (feature, "CBB0", 162, 1, "audio", 32, "int");
  tdesc_create_reg (feature, "CBB1", 163, 1, "audio", 32, "int");
  tdesc_create_reg (feature, "CBB2", 164, 1, "audio", 32, "int");
  tdesc_create_reg (feature, "CBB3", 165, 1, "audio", 32, "int");
  tdesc_create_reg (feature, "CBE0", 166, 1, "audio", 32, "int");
  tdesc_create_reg (feature, "CBE1", 167, 1, "audio", 32, "int");
  tdesc_create_reg (feature, "CBE2", 168, 1, "audio", 32, "int");
  tdesc_create_reg (feature, "CBE3", 169, 1, "audio", 32, "int");

  tdesc_nds32 = result;
}
